// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import Notification from 'stimulus-notification'
import Flatpickr from 'stimulus-flatpickr'
import NestedForm from 'stimulus-rails-nested-form'
import { Alert, Autosave, Dropdown, Modal, Tabs, Popover, Toggle, Slideover } from "tailwindcss-stimulus-components"

application.register('notification', Notification)
application.register('flatpickr', Flatpickr)
application.register('nested-form', NestedForm)
// Register all TailwindCSS Components
application.register('alert', Alert)
application.register('autosave', Autosave)
application.register('dropdown', Dropdown)
application.register('modal', Modal)
application.register('tabs', Tabs)
application.register('popover', Popover)
application.register('toggle', Toggle)
application.register('slideover', Slideover)
