databases:
  - name: postgres_casa_laterite_prod
    databaseName: casa_laterite_production
    region: frankfurt
    plan: free
    ipAllowList: []

services:
  - type: redis
    name: sidekiq-redis_casa_laterite
    region: frankfurt
    plan: free
    maxmemoryPolicy: noeviction
    ipAllowList: [] # only allow internal connections

  - type: worker
    name: sidekiq-worker_casa_laterite
    plan: starter
    env: ruby
    region: frankfurt
    buildCommand: bundle install
    startCommand: bundle exec sidekiq
    envVars:
      - key: REDIS_URL
        fromService:
          type: redis
          name: sidekiq-redis_casa_laterite
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
  - type: web
    name: casa_laterite
    env: ruby
    region: frankfurt
    plan: free
    buildCommand: bundle install; bundle exec rake assets:precompile; bundle exec rake assets:clean; bundle exec rake db:migrate;
    startCommand: bundle exec puma -t 5:5 -p ${PORT:-3000} -e ${RACK_ENV:-development}
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgres_casa_laterite_prod
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: sidekiq-redis_casa_laterite
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
